name: 'Build base devcontainer image'
on:
  push:
    paths:
      - '.devcontainer/base/**'
    branches:
      - main
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:  
        - name: Checkout (GitHub)
          uses: actions/checkout@v3  
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}  
        - name: 'Pre-build devcontainer image'
          uses: devcontainers/ci@v0.3
          with:
            imageName: ghcr.io/azure-samples/cosmos-db-design-patterns/devcontainer
            noCache: true
            push: always
